//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "menu")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub parent_id: i64,
    pub path: String,
    #[sea_orm(unique)]
    pub name: String,
    pub component: String,
    pub redirect: Option<String>,
    pub sort: i32,
    pub meta: Option<Json>,
    pub status: i8,
    pub remark: Option<String>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
