//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

pub mod custom_parameter;
pub mod database_info;
pub mod domain;
pub mod endpoint;
pub mod menu;
pub mod report;
pub mod report_detail;
pub mod repository;
pub mod repository_detail;
pub mod schedule;
pub mod task;
pub mod user;
