//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

pub use super::custom_parameter::Entity as CustomParameter;
pub use super::database_info::Entity as DatabaseInfo;
pub use super::domain::Entity as Domain;
pub use super::endpoint::Entity as Endpoint;
pub use super::menu::Entity as Menu;
pub use super::report::Entity as Report;
pub use super::report_detail::Entity as ReportDetail;
pub use super::repository::Entity as Repository;
pub use super::repository_detail::Entity as RepositoryDetail;
pub use super::schedule::Entity as Schedule;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
