//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "report_detail")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub report_id: i64,
    pub content_type: String,
    #[sea_orm(column_type = "custom(\"mediumblob\")", nullable)]
    pub content: Option<String>,
    pub created_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
